name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/callELPSYCONGROO/influxdb.git /opt/influxdb
    - name: Build the Docker image
      run: | 
        cd /opt/influxdb
        docker build . --file Dockerfile --tag inview/influxdb:v1
        mkdir -p /opt/images
        docker save -o /opt/images/influxdb.tar inview/influxdb
        cd /opt/images
        bzip2 -c influxdb.tar
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: influxdb
        path: /opt/images
       
